# Generated by Django 3.1.7 on 2021-03-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210312_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='Desciption goes here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
